<?php
/*======================================================================*\
|| #################################################################### ||
|| # Package - Joomla Template based on YJSimpleGrid Framework          ||
|| # Copyright (C) 2010  Youjoomla.com. All Rights Reserved.            ||
|| # license - PHP files are licensed under  GNU/GPL V2                 ||
|| # license - CSS  - JS - IMAGE files  are Copyrighted material        ||
|| # bound by Proprietary License of Youjoomla.com                      ||
|| # for more information visit http://www.youjoomla.com/license.html   ||
|| # Redistribution and  modification of this software                  ||
|| # is bounded by its licenses                                         ||
|| # websites - http://www.youjoomla.com | http://www.yjsimplegrid.com  ||
|| #################################################################### ||
\*======================================================================*/
defined( '_JEXEC' ) or die( 'Restricted index access' );
/*  
  !!! DO NOT EDIT THIS FILE. IT MIGHT BE CHANGED ON UPDATE
  this file is custom for this template only. if you wish to edit or add 
  own code to the template, use template_name/custom/yjsg_custom_params.php
  
*/
/*

	this variable is for custom link color. you can use it to style any HTML elements
	see instructions here:
	http://www.yjsimplegrid.com/documentation/advanced/elements-styling-based-on-link-color.html

*/
	
$cc_css ="a{color:".$style_color.";}";

// custom bootstrap buttons backgrounds per style. Bypassing the template link color and going with template hover instead 
switch ($css_file) {
    case 'blue':
        $valid_color = '00aff0';
        break;
    case 'pink':
        $valid_color = 'ff4dc2';
        break;
    case 'red':
        $valid_color = 'ff3333';
        break;
        default:
       $valid_color = 'ff5512';
}

/* K2 CSS */
if (JFactory::getApplication()->input->get( 'option' ) == 'com_k2' 
	|| JModuleHelper::getModule( 'k2_content' )
	|| JModuleHelper::getModule( 'k2_tools' )
	|| JModuleHelper::getModule( 'k2_comments' )
	){
		$document->addStyleSheet($yj_site.'/css/customk.css');
}

/*JS IMAGE EFFECT */
$YjsgCustomJS	= array();
$YjsgCustomJS[] = $yj_site.'/src/styles.js';


/*-- TOP MENU LOCATION --*/
$topMenuLocation 	 = 1; // 1 = inside the header block next to logo

/*-- TOP MENU VERTICAL OFFSET --*/
$DDverticalTopOffset = 78;// SmoothDropdown
$module = JModuleHelper::getModule( 'mod_yjis4' );
$bg_switch = '';
if (isset($module)){
	$bg_switch =' active';
}

?>
